site_name: "AdmixIT"
site_dir: public
docs_dir: ./docs
theme:

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

extra:
  generator: false
  social:
    - icon: fontawesome/solid/rss
      link: https://Admixit.com
extra_css:
  - assets/extra.css
extra_javascript:
  - assets/checklist.js
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search:
      lang: en
  - roamlinks 
