site_name: "AdmixIT"
site_dir: public
docs_dir: ./docs

theme:
  name: 'material'
  favicon: 'assets/favicon.ico'
  logo: 'assets/favicon.ico'
  icon:
    repo: fontawesome/brands/git-alt
  features:
    #- navigation.instant
    - navigation.tabs
    - navigation.sections
    #- navigation.expand
    - navigation.top
    #- header.autohide    # hides header completely when scrolling down
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: black  
      accent: orange
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: black 
      accent: orange

extra:
  # Link to go when logo clicked
  homepage: https://docs.Admixit.com

plugins:
  - search
  - include-markdown
  - roamlinks

  # mermaid2 diagrams: https://mermaid-js.github.io/mermaid/#/
  - mermaid2:
      arguments:
        theme: forest   # default, forest, dark, neutral, base
        themeCSS: ".er.entityLabel{fill: black;} .messageLine0{stroke: orange;} .messageLine1{stroke: orange;} #arrowhead{fill: orange;} .messageText{fill: black; stroke: black}"    
  #- pdf-export
  # - with-pdf:
  #     output_path: /home/document.pdf
  #     exclude_pages:
  #          - 'home/'
  #     two_columns_level: 3
  # This will allow autodocumentation of python code from the projects cloned in the parent of this dir
  # - mkdocstrings:
  #     handlers:
  #           python:
  #               setup_commands:
  #                   - import sys
  #                   - sys.path.append('../')

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed
  - abbr
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.escapeall
  - pymdownx.smartsymbols
  - pymdownx.tilde:
      smart_delete: true
  - footnotes

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
          
 
