site_name: "Lille Ø Handbook"
site_dir: public
docs_dir: ./docs
theme:
  name: material
  logo: assets/favicon.png
  homepage: https://lille-oe.de
  favicon: assets/boat.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.footer
extra:
  generator: false
  social:
    - icon: fontawesome/solid/rss
      link: https://lille-oe.de
extra_css:
  - assets/extra.css
extra_javascript:
  - assets/checklist.js
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search:
      lang: en
  - roamlinks 
